# Generated by Django 3.1.1 on 2020-09-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentor_Name', models.CharField(default='', max_length=50)),
                ('Student_Name', models.CharField(default='', max_length=50)),
                ('Status', models.CharField(default='', max_length=50)),
                ('Remark', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
